<a href="https://colab.research.google.com/github/derektorquette/estatistica-para-analise-de-dados-com-python/blob/main/7_estatistica_probabilistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PROBABILIDADE**

In [1]:
import numpy as np
import pandas as pd

In [2]:
enem_sp = pd.read_csv('/content/enem_2019_tratado.csv',
                      sep=',', encoding='iso-8859-1')

In [3]:
enem_guarulhos = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Guarulhos']

In [4]:
enem_bauru = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Bauru']

In [5]:
enem_guarulhos.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
4,"1,90E+11",Guarulhos,23,F,1,branca,1,1,não_respondeu,NaN,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim
56,"1,90E+11",Guarulhos,17,F,1,parda,1,2,pública,NaN,...,468.1,Espanhol,1.0,100.0,60.0,60.0,100.0,0.0,320.0,Sim
69,"1,90E+11",Guarulhos,27,M,1,nao_declarado,1,1,não_respondeu,NaN,...,743.8,Inglês,1.0,120.0,180.0,120.0,120.0,160.0,700.0,Sim
130,"1,90E+11",Guarulhos,28,F,1,branca,1,1,não_respondeu,NaN,...,415.1,Inglês,1.0,160.0,120.0,160.0,120.0,100.0,660.0,Sim
202,"1,90E+11",Guarulhos,17,F,1,parda,1,2,pública,35005824.0,...,594.9,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim

In [6]:
enem_bauru.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
477,"1,90E+11",Bauru,21,M,1,branca,1,1,não_respondeu,NaN,...,664.1,Inglês,1.0,100.0,120.0,120.0,120.0,100.0,560.0,Sim
928,"1,90E+11",Bauru,17,M,1,amarela,1,2,pública,35025240.0,...,740.3,Inglês,1.0,140.0,120.0,120.0,140.0,100.0,620.0,Sim
1070,"1,90E+11",Bauru,19,M,1,branca,1,1,não_respondeu,NaN,...,789.2,Inglês,1.0,160.0,200.0,200.0,200.0,200.0,960.0,Sim
1235,"1,90E+11",Bauru,18,F,1,parda,1,2,privada,35115435.0,...,71.5,Inglês,1.0,140.0,140.0,140.0,140.0,120.0,680.0,Sim
1506,"1,90E+11",Bauru,19,M,1,branca,1,1,não_respondeu,NaN,...,533.8,Espanhol,1.0,120.0,140.0,120.0,100.0,140.0,620.0,Sim

In [7]:
enem_guarulhos.shape

(11054, 28)

In [12]:
enem_bauru.shape

(2929, 28)

In [8]:
len(enem_guarulhos)

11054

In [9]:
len(enem_bauru)

2929

In [10]:
len(enem_sp)

352189

In [13]:
# CRIANDO FUNÇÃO PROBABILIDADE
def probab (A, E):
  resultado = (A / E)*100
  print('{:.2f}'.format(resultado))

In [14]:
# PROBABILIDADE DE RETIRAR UM VESTIBULANDO DE GUARULHOS
probab (len(enem_guarulhos), len(enem_sp))

3.14

In [15]:
# PROBABILIDADE DE RETIRAR UM VESTIBULANDO DE BAURU
probab (len(enem_bauru), len(enem_sp))

0.83

## Probabilidade de não ocorrer um evento

In [16]:
# CRIANDO FUNÇÃO PROBABILIDADE DE NÃO OCORRER UM EVENTO
def probab_nao (A, E):
  resultado = (1- (A / E))*100
  print('{:.2f}'.format(resultado))

In [17]:
# PROBABILIDADE DE NÃO RETIRAR UM VESTIBULANDO DE GUARULHOS
probab_nao (len(enem_guarulhos), len(enem_sp))

96.86

In [19]:
# PROBABILIDADE DE NÃO RETIRAR UM VESTIBULANDO DE GUARULHOS E NEM DE BAURU
probab_nao (len(enem_guarulhos)+len(enem_bauru), len(enem_sp))

96.03

## Probabilidade da união mutuamente exclusivos (AUB)

In [20]:
# CRIANDO FUNÇÃO PROBABILIDADE DA UNIÃO MUTUAMENTE EXCLUSIVOS (AUB)
# A = evento a ; B = evento b ; E = espaço amostral
def probab_uniao (A, B, E):
  resultado = (A/E + B/E)*100
  print('{:.2f}'.format(resultado))

In [21]:
# PROBABILIDADE DE RETIRAR UM VESTIBULANDO DE GUARULHOS OU DE BAURU
probab_uniao(len(enem_guarulhos),len(enem_bauru),len(enem_sp))

3.97

## Probabilidade da Intersecção de dois eventos

In [23]:
# CRIANDO FUNÇÃO PROBABILIDADE DA INTERSECÇÃO DE DOIS EVENTOS INDEPENDENTES
# A = evento a; B = evento b
def probab_inter (A, B, E):
  resultado = (A/E * B/E)*100
  print('{:.3f}'.format(resultado))

In [25]:
# PROBABILIDADE DE RETIRAR UM VESTIBULANDO DE GUARULHOS E DE BAURU (com reposição)
probab_inter(len(enem_guarulhos),len(enem_bauru),len(enem_sp))

0.026

## Probabilidade Condicional

In [26]:
#CRIANDO FUNÇÃO PROBABILIDADE CONDICIONAL
# AB = evento a dado b
def probab_cond (AB, B):
  resultado = (AB / B)*100
  print('{:.2f}'.format(resultado))

In [34]:
#PROBABILIDADE DE RETIRAR UMA MULHER PARDA
mulher = enem_sp.loc[enem_sp.SEXO == 'F']

In [35]:
mulher_parda = mulher.loc[mulher.RACA == 'parda']

In [36]:
mulher_parda.head(5)

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
1,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,15567761.0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
3,"1,90E+11",Embu-Guaçu,17,F,1,parda,1,2,pública,NaN,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
7,"1,90E+11",Santo André,20,F,1,parda,1,1,não_respondeu,NaN,...,508.5,Espanhol,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim
9,"1,90E+11",Santo André,44,F,2,parda,1,1,não_respondeu,NaN,...,488.1,Espanhol,1.0,120.0,120.0,120.0,120.0,40.0,520.0,Sim
11,"1,90E+11",Guará,17,F,1,parda,1,2,pública,35023310.0,...,535.1,Inglês,1.0,140.0,120.0,140.0,160.0,120.0,680.0,Sim

In [38]:
mulher_parda.shape

(66268, 28)

In [30]:
probab_cond(len(mulher_parda),len(mulher))

30.84